### ISSUE TITLE
Ploblem importing pip installed flask_assets 

### ISSUE THREAD

**Issue by xtiansimon** [toddbirchard/flasklogin-tutorial#4]
I'm working on the Hackers&Slackers tutorial for [Flask login][1] and testing the code cloned from this [github repo][2] without modification. I'm developing on Arch Linux using mostly Arch python packages, and I pip installed your requirements.txt into a venv (note: is it necessary to pip install the demo itself? if yes, then package name has changed; and I didn not install it). I ran the tutorial code and a helloworld test import of Flask-Assets in the same terminal and venv with `FLASK_ENV=development`, `FLASK_APP=wsgi.py`.

Running the tutorial report I'm getting this exception (see more below),

    from flask_assets import Environment, Bundle
    ModuleNotFoundError: No module named 'flask_assets'

The thing is, `Flask-Assets 2.0` is installed with pip in my virtual environment as demonstrated by a simple helloworld Flask app:

```
    from flask import Flask
    from flask_assets import Environment, Bundle
    import inspect
    
    sl = []
    for key, data in inspect.getmembers(Environment, inspect.isclass): 
       sl.append('{}:{!r}'.format(key, data)) 
    
    s = ' '.join(map(str, sl)) 
    
    app = Flask(__name__)
    app.debug = True
    
    @app.route("/")
    def hello():
        return s
    
    if __name__ == "__main__":
        app.run()
```
The helloworld test page evidently access the Flask extension, because it returns recognizable results: `__class__: config_storage_class: resolver_class:...`

Have you encountered anything similar while you were developing this tutorial?

```
flask.cli.NoAppException

flask.cli.NoAppException: While importing "wsgi", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/moltar/xtian/Documents.x/Work.d/RBC.d/PyAuto_Framework.d/www/flasklogin-tutorial/wsgi.py", line 4, in <module>
    app = create_app()
  File "/home/moltar/xtian/Documents.x/Work.d/RBC.d/PyAuto_Framework.d/www/flasklogin-tutorial/flask_login_tutorial/__init__.py", line 23, in create_app
    from . import routes
  File "/home/moltar/xtian/Documents.x/Work.d/RBC.d/PyAuto_Framework.d/www/flasklogin-tutorial/flask_login_tutorial/routes.py", line 5, in <module>
    from .assets import compile_auth_assets
  File "/home/moltar/xtian/Documents.x/Work.d/RBC.d/PyAuto_Framework.d/www/flasklogin-tutorial/flask_login_tutorial/assets.py", line 1, in <module>
    from flask_assets import Environment, Bundle
ModuleNotFoundError: No module named 'flask_assets'

```

  [1]: https://hackersandslackers.com/flask-login-user-authentication
  [2]: https://github.com/toddbirchard/flasklogin-tutorial

**Comment by xtiansimon** [comment]
Something wrong with my virtual environment
